[package]
name = "porkbun-ddns-rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "porkbun_ddns_rs"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
public-ip = { version = "0.2" }
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
dirs = { version = "5" }
clap = { version = "4", features = ["derive"] }
log = { version = "0.4" }
env_logger = { version = "0.11" }
